# Generated by Django 5.2.1 on 2025-05-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='bonus',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supply',
            name='exchange',
            field=models.SmallIntegerField(default=0),
        ),
    ]
