# Generated by Django 5.2.1 on 2025-05-11 08:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_management', '0002_alter_supply_bonus_alter_supply_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='delivery_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
