# Generated by Django 5.2.1 on 2025-05-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_management', '0003_supply_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
