# Generated by Django 5.2.1 on 2025-05-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_management', '0004_alter_supply_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='delivery_date',
            field=models.DateField(db_index=True),
        ),
    ]
