# Generated by Django 5.2.1 on 2025-05-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_management', '0005_alter_supply_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='comment',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
    ]
