# Generated by Django 5.2.1 on 2025-05-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_management', '0006_supply_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
