# Generated by Django 5.2.1 on 2025-05-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_management', '0007_alter_supply_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
