# Generated by Django 5.2.1 on 2025-05-14 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_clientdebt_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdebt',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='app.client'),
        ),
    ]
