# Generated by Django 5.2.1 on 2025-05-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cashflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
