# Generated by Django 5.2.1 on 2025-05-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_cashflow_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supply',
            old_name='price',
            new_name='price_bank',
        ),
        migrations.AddField(
            model_name='supply',
            name='price_cash',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
