# Generated by Django 5.2.1 on 2025-05-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_price_supply_price_bank_supply_price_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
