# Generated by Django 5.2.1 on 2025-05-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_supply_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='last_accessed',
            field=models.DateTimeField(),
        ),
    ]
