# Generated by Django 5.2.1 on 2025-05-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_supplier_last_accessed'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='confirmation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
