# Generated by Django 5.2.1 on 2025-05-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_confirmation_time_supply_confirmation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='confirmation_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
