# Generated by Django 5.2.1 on 2025-05-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_supply_confirmation_date_supply_arrival_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='is_everyday_supply',
            field=models.BooleanField(default=False),
        ),
    ]
