# Generated by Django 5.2.1 on 2025-05-28 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_supplier_is_everyday_supply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashflow',
            options={'verbose_name': 'Внос/вынос денег', 'verbose_name_plural': 'Внос/вынос денег'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='clientdebt',
            options={'verbose_name': 'Долг', 'verbose_name_plural': 'Долги'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Поставщик', 'verbose_name_plural': 'Поставщики'},
        ),
        migrations.AlterModelOptions(
            name='supply',
            options={'verbose_name': 'Поставка', 'verbose_name_plural': 'Поставки'},
        ),
        migrations.CreateModel(
            name='SupplierExtraData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('supervisor', 'Супервайзер'), ('representative', 'Торговый представитель'), ('delivery', 'Доставка')], max_length=20)),
                ('name', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=25)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.supplier')),
            ],
        ),
    ]
