# Generated by Django 5.2.1 on 2025-05-29 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_supplier_delivery_supplier_delivery_pn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='supplier', to='app.supplier'),
        ),
    ]
