# Generated by Django 5.2.1 on 2025-08-03 08:24

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_supply_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(db_index=True, max_length=25, unique=True, verbose_name='именем'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='supplier',
            field=models.ForeignKey(default=app.models.get_default_supplier, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='supplier', to='app.supplier'),
        ),
    ]
