# Generated by Django 5.2.1 on 2025-08-03 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdebt',
            name='responsible_employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.employee'),
            preserve_default=False,
        ),
    ]
