# Generated by Django 5.2.1 on 2025-08-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_clientdebt_responsible_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
