# Generated by Django 5.2.4 on 2025-08-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_supplier_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='invoice',
            field=models.FileField(blank=True, upload_to='pdfs/'),
        ),
    ]
