# Generated by Django 5.2.4 on 2025-08-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_supply_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='invoice_html',
            field=models.TextField(blank=True),
        ),
    ]
