# Generated by Django 4.2.25 on 2025-11-02 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_supply_invoice_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply',
            name='invoice',
        ),
    ]
