# Generated by Django 4.2.25 on 2025-12-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_supply_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='is_rescheduled',
            field=models.BooleanField(default=False),
        ),
    ]
