# Generated by Django 4.2.25 on 2025-12-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_supply_is_rescheduled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply',
            name='is_rescheduled',
        ),
        migrations.AddField(
            model_name='supply',
            name='rescheduled_cnt',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
