# Generated by Django 4.2.25 on 2025-12-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_supply_is_rescheduled_supply_rescheduled_cnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdebt',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientdebt',
            name='repaid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
