# Generated by Django 4.2.25 on 2025-12-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_clientdebt_is_valid_clientdebt_repaid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdebt',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
