# Generated by Django 4.2.25 on 2025-12-27 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0033_remove_store_owner_alter_userprofile_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cashflows', to='app.store'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='app.store'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='owner',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner_store', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='app.store'),
            preserve_default=False,
        ),
    ]
