# Generated by Django 4.2.25 on 2025-12-27 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_cashflow_store_client_store_store_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='store',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='app.store'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='store',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashflows', to='app.store'),
        ),
        migrations.AlterField(
            model_name='client',
            name='store',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='app.store'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='store',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='app.store'),
        ),
    ]
