# Generated by Django 4.2.25 on 2025-12-27 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_supply_store_alter_cashflow_store_alter_client_store_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='owner',
        ),
        migrations.AlterField(
            model_name='supply',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='app.supplier'),
        ),
    ]
