# Generated by Django 4.2.25 on 2025-12-28 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0036_remove_store_owner_alter_supply_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdebt',
            name='responsible_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
