# Generated by Django 4.2.25 on 2026-01-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_alter_clientdebt_responsible_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
