# Generated by Django 4.2.25 on 2026-01-05 09:45

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='supplyimage',
            name='image',
            field=models.ImageField(upload_to=app.models.upload_to),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('name', 'store'), name='unique_supplier_per_store'),
        ),
    ]
