# Generated by Django 4.2.25 on 2026-01-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_supplier_name_alter_supplyimage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='supply',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('confirmed', 'Подтверждена'), ('delivered', 'Доставлена'), ('cancelled', 'Отменена')], default='pending', max_length=30),
        ),
    ]
