# Generated by Django 4.2.25 on 2026-01-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_remove_supply_is_confirmed_supply_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='status',
            field=models.CharField(choices=[('pending', 'Не подтверждена'), ('confirmed', 'Ожидает оплаты'), ('delivered', 'Подтверждена')], default='pending', max_length=30),
        ),
    ]
